### ISSUE TITLE
Feature request: more advanced Puppetfile support

### ISSUE THREAD

**Issue by rogermartensson** [lingua-pupuli/puppet-vscode#286] opened 2018-06-08 08:49 UTC
Wouldn't it be nice if it was possible to check modules in Puppetfile against forge.puppet.com.
Features I can think of are:
- basic checks against  Puppetfile syntax
- syntax highlighting
- check for newer versions on modules on Forge
- check for missing dependencies
- Help on syntax

Just some of my ideas. They are not that simple to implement but I hope you will consider them and put them on your future-todo-list. 

My personal favorite are version checks agains Forge. A feature that would be really nice to have when working on a Puppetfile with many many modules. Right after that is dependency checks but that one might be much harder to implement.

**Comment by glennsarti** [comment] 2018-06-09 13:16
Hi @rogermartensson .  I'm closing this off as a duplicate of https://github.com/lingua-pupuli/puppet-editor-services/issues/28

The good news is point 1 of your list will be available in the next release of the extension

**Closed** 2018-06-09 13:18 UTC
