### ISSUE TITLE
add rocket autoindentation

### ISSUE THREAD

**Issue by tuxmea** [lingua-pupuli/puppet-vscode#390] opened 2018-10-07 15:27 UTC
**Summary of the new feature**

When typing Puppet code, I want the IDE to automatically indent rocket characters (e.g. on parameters and properties at type declaration)

For example:

```
1 user { 'root':
2   ensure => home,
3   managehome => true,
4 }
```

Upon adding line 3, the rocket from line 2 should be aligned to the one in line 3.

**Comment by jpogran** [comment] 2018-10-08 01:53
Thanks for the feature suggestion. This was partly raised in #289, the autoindent functionality in VSCode is in two parts. The user 9you) have to enable it in the VSCode settings, as well as the extension implementing a `indentationRules` block. We did some work to enable this for other parts of the DSL, but as explained in that ticket its trickier to implement the type declaration like you provide above.

Until this is fully addressed, you can take advantage of other extensions that handle alignment in general. We recommend https://marketplace.visualstudio.com/items?itemName=wwm.better-align. Granted, this requires a key combination press but its better than no alignment.

**Comment by tuxmea** [comment] 2018-10-08 07:00
@jpogran many thanks for pointing me to the extension. I tried it, but the extension also needs to learn about Puppet DSL. It would be great if we get alignment directly into the Puppet extension.
Feel free to close, if #289 covers this request.

**Comment by glennsarti** [comment] 2018-10-08 07:57
Heya @tuxmea.  There is an alternate solution too.  The Puppet Extension supports the "Format Document" command, which behind the scenes runs puppet-lint and fixes any issues.  VSCode also has a feature called Format Document on Save, which effectively runs puppet-lint prior to you saving your document.

So while it won't fix it as you type, it could fix it on save.

Due to the way puppet-lint is written we can't easily apply fixes for a single rule, but we're always looking at ways to do it.

Note - For some reason linting is broken on my dev laptop, so I'll need to try a fresh install.  If it's still broken then I'll log a separate issue.

**Comment by glennsarti** [comment] 2018-10-08 08:03
Confirmed on a fresh VM, linting and format document are working fine.

**Comment by jpogran** [comment] 2018-10-15 17:04
@tuxmea I'm going follow your suggestion to close this issue as the core suggestion is being tracked in #289. Thanks for the suggestion and thanks for using our extension!

**Closed by jpogran** 2018-10-15 17:04 UTC
Labels: feature
