### ISSUE TITLE
puppet node graph error

### ISSUE THREAD

**Issue by jrbast** [lingua-pupuli/puppet-vscode#577] opened 2019-11-06 21:21 UTC
There were no resources created in the node graph. Is there an include statement missing?

**Comment by jpogran** [comment] 2019-11-07 15:35
Hi @jrbast , could you fill out the information in the new issue request? It will help us answer your question. Otherwise, all I have is the error message above.

**Comment by jrbast** [comment] 2019-11-07 15:53
How do I do that.. never done this before??

Thank you,
Jeff

Jeff Bast
IT Server Analyst Lead
TECH - Hybrid Cloud Platform Services

[cid:image001.png@01CF1C1B.B7FDEC00][schneider1]
3101 S. Packerland Drive, Green Bay, WI 54306
•  920.592.8368  •  800.558.6767 ext.5928368  • bastj@schneider.com<mailto:andersonje@schneider.com>
Working hours: Monday thru Friday 7:00am - 4:00pm
Mail-stop: US.GRB.01.03.11

The information contained in this e-mail is privileged and confidential, and for use only of the addressees of same and/or those who might have been specifically authorized to read it.  If you have received this e-mail by error, please destroy it and notify the sender, to his/her e-mail address.  Any non-authorized dissemination, distribution or reproduction of this message is strictly prohibited, and subject to the sanctions established in the applicable laws.

**Comment by jpogran** [comment] 2019-11-07 15:55
No worries! When you create a new issue with https://github.com/lingua-pupuli/puppet-vscode/issues/new/choose, it presents several choices. Choosing bug report lists this template, which you can then answer inline:


### What Versions are you running?

OS Version:
VSCode Version:
Puppet Extension Version:
PDK Version:



### What You Are Seeing?

### What is Expected?

### How Did You Get This To Happen? (Steps to Reproduce)



### Output Log

**Comment by jpogran** [comment] 2019-11-08 15:09
Duplicate of #578

**Closed by jpogran** 2019-11-08 15:09 UTC
